version: '3'

services:
  server_manager:
    image: cartesi/host-server-manager:0.2.1
    environment:
      - DAPP_HTTP_ADDRESS=host.docker.internal
    ports:
      - "5004:5004"
    extra_hosts:
      - "host.docker.internal:host-gateway"
