version: '3'

services:
  hardhat:
    build: ./contracts
    command: ["node", "--write", "true", "--network", "hardhat", "--export", "/opt/cartesi/share/blockchain/localhost.json"]
    platform: linux/amd64
    init: true
    ports:
      - '8545:8545'
    volumes:
      - ./contracts/export/abi:/opt/cartesi/share/blockchain

  rollups_dispatcher:
    depends_on: [hardhat]
    image: cartesi/rollups-dispatcher:0.1.2
    restart: always
    platform: linux/amd64
    environment:
      # TODO: currently hardhat's default mnemonic
      # this should become a secret
      - MNEMONIC=test test test test test test test test test test test junk
      - CHAIN_ID=31337
      - RUST_LOG=info
      - LOGIC_CONFIG_PATH=/opt/cartesi/share/config/logic-config.toml
      - STATE_FOLD_CONFIG_PATH=/opt/cartesi/share/config/sf-config.toml
      - BLOCK_SUBSCRIBER_CONFIG_PATH=/opt/cartesi/share/config/bs-config.toml
      - TX_MANAGER_CONFIG_PATH=/opt/cartesi/share/config/tm-config.toml
      - STATE_SERVER_HOSTNAME=state_server
      - STATE_SERVER_PORT=50051
      - SERVER_MANAGER_HOSTNAME=server_manager
      - SERVER_MANAGER_PORT=5001
      - DEPLOYMENT_PATH=/opt/cartesi/share/blockchain/localhost.json
    volumes:
      - ./contracts/export/abi:/opt/cartesi/share/blockchain:ro
      - ./config:/opt/cartesi/share/config/

  state_server:
    depends_on: [hardhat]
    image: cartesi/delegate-server:0.1.2
    restart: always
    platform: linux/amd64
    environment:
      - STATE_FOLD_CONFIG_PATH=/opt/cartesi/share/config/sf-config.toml
      - DEPLOYMENT_PATH=/opt/cartesi/share/blockchain/localhost.json
      - URL=http://hardhat:8545
    volumes:
      - ./contracts/export/abi:/opt/cartesi/share/blockchain:ro
      - ./config:/opt/cartesi/share/config/

  server_manager:
    image: cartesi/host-server-manager:0.2.1
    platform: linux/amd64
    environment:
      - DAPP_HTTP_ADDRESS=host.docker.internal
    ports:
      - "5004:5004"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rollups_indexer:
    depends_on: [hardhat]
    image: cartesi/rollups-indexer:0.1.2
    restart: always
    platform: linux/amd64
    environment:
      - URL=http://hardhat:8545
      - INDEXER_CONFIG_PATH=/opt/cartesi/share/config/indexer-config.toml
      - STATE_SERVER_HOSTNAME=state_server
      - STATE_SERVER_PORT=50051
      - SERVER_MANAGER_HOSTNAME=server_manager
      - SERVER_MANAGER_PORT=5001
      - DEPLOYMENT_PATH=/opt/cartesi/share/blockchain/localhost.json
      - POSTGRES_HOSTNAME=database
      - POSTGRES_PORT=5432
    volumes:
      - ./contracts/export/abi:/opt/cartesi/share/blockchain
      - ./config:/opt/cartesi/share/config/

  query_server:
    image: cartesi/query-server:0.1.2
    platform: linux/amd64
    ports:
      - '4000:4000'
    links:
      - database
    depends_on:
      - database
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB_TEST_NAME=postgres
      - URL=http://hardhat:8545

  database:
    image: postgres:12
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database-data:/var/lib/postgresql/data

  provy_server:
    depends_on:
      - hardhat
    links:
      - hardhat
    ports:
      - '8000:8000'
    build: ./proxy
    working_dir: /var/www/
    volumes:
      - ./proxy:/var/www
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  database-data: {}
