[logic_config]

# unique session identifier for machine manager
session_id = "default_rollups_id"

# node starts syncing from inital epoch
initial_epoch = 0

# gas estimation/price multiplier
gas_multiplier = 1
gas_price_multiplier = 1

# number of blocks before resubmting tx
rate = 20

# depth of blocks before considering tx finalized
confirmations = 10

# end points
provider_http_endpoint = "http://hardhat:8545"
ws_endpoint = "ws://hardhat:8545"
state_fold_grpc_endpoint = "http://state_server:50051"
mm_endpoint = "http://server_manager:5001"
