# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Echo (Python)
on:
  push:
    paths:
      - "echo/**"
      - ".github/workflows/echo-python.yml"
jobs:
  build_machine:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Cartesi Machine
        working-directory: echo
        run: make machine

      - name: Save Cartesi Machine Artifact
        uses: actions/upload-artifact@v2
        with:
          name: echo-python-machine
          path: echo/machine
          retention-days: 7

      - name: Package Cartesi Machine
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: echo/machine
        run: zip -r ../echo-python-machine-${GITHUB_REF:11}.zip .

      - name: Publish Cartesi Machine
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: echo/echo-python-machine-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
